//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawlerDataTest.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class ContentInfo
    {
        #region 基本属性
    
        [DataMember]
        public string ID { get; set; }
        [DataMember]
        public string Title { get; set; }
        [DataMember]
        public string Content { get; set; }
        [DataMember]
        public string ContentAbstract { get; set; }
        [DataMember]
        public string InformationSource { get; set; }
        [DataMember]
        public System.DateTime PublishTime { get; set; }
    

        #endregion
    }
}
