//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawlerDataTest.DataAccess.Entities
{
    using System;
    using System.Data.Entity;
    
    public partial class CrawlerDataEntities : DbContext
    {
        public CrawlerDataEntities()
            : base("name=CrawlerDataEntities")
        {
    	this.Configuration.ProxyCreationEnabled = false;
        }
    
        public DbSet<ContentInfo> ContentInfo { get; set; }
    }
}
